server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KnowledgeQuiz?characterEncoding=UTF-8
    username: root
    password: Knowledge123!
    #password: Pabao.z5Yv
    #password: webgoat...
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

appinfo:
  appid: wxd85b8532ae26b621
  appsecret: 29d0dc633c4601b90f8f045f0f4fcef8
